[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  functions = "netlify/functions"

# [[plugins]]
#   package = "@netlify/plugin-schedule"
#
#   [plugins.inputs]
#     functions = [
#       { path = "birthday-checker", schedule = "0 10 * * *" }
#     ]
#
# NOTE: The @netlify/plugin-schedule is not available on npm and cannot be installed locally. Uncomment this block ONLY for production deployment, not for local dev.
