[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-schedule"

  [plugins.inputs]
    functions = [
      { path = "birthday-checker", schedule = "0 10 * * *" }
    ]
