[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  functions = "netlify/functions"

[functions."birthday-checker"]
  schedule = "0 10 * * *"
# This will schedule the birthday-checker function to run every day at 10:00 AM UTC (adjust for your timezone as needed).
